required: sudo
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_d4052613cb38_key -iv $encrypted_d4052613cb38_iv -in multi-k8s-283910-d3dfcdc3744f.json.enc -out multi-k8s-283910-d3dfcdc3744f.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/goohle-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file multi-k8s-283910-d3dfcdc3744f.json
    - gcloud set project multi-k8s-283910
    - gcloud config set compute/zone us-central1-c
    - gcloud container clusters get-credentials mutli-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t invicit/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true invicit/react-test npm test -- --coverage

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master